name: event_hub_app
description: A new Flutter project.
publish_to: 'none'  # Adjust if I publish this app
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  intl: ^0.18.0
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.15
  http: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  share: ^2.0.4
  sqflite: ^2.0.0+4  # Add sqflite for SQLite database integration
  path: ^1.8.3
  mockito: ^5.0.0
  build_runner: ^2.0.0
  intl_translation: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/eventhub_logo.png
    - lib/assets/images/concert.jpg
    - lib/assets/images/art_exhibition.jpg
    - lib/assets/images/theatre_play.jpg
